# Generated by Django 4.2.7 on 2023-12-01 19:07

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customuser_managers_customuser_is_banned_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='discord_server_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='id пользователя дискорд'),
        ),
    ]
